spring:
  application:
    name: mycrm-config-server
    
  profiles:
    active: git
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ignatony/my-crm
          search-paths: config
    
